jobs:
  include:
  - stage: dev
    name: "dev run"
    if: branch = dev
    addons:
      ssh_known_hosts: 34.85.95.83
    language: go
    go:
    - '1.14'
    script: echo "no test in dev"
    before_install:
    - openssl aes-256-cbc -K $encrypted_d523664c6f66_key -iv $encrypted_d523664c6f66_iv
      -in build/id_rsa.enc -out ~/.ssh/id_rsa -d
    - chmod 600 ~/.ssh/id_rsa
    after_success:
    - ssh root@34.85.95.83 'cd /root/work/go/y-transport-server && sh ./build/dev.sh'
  include:
  - stage: prd
    name: "prd run"
    if: branch = master
    language: go
    go:
    - '1.14'
    addons:
      ssh_known_hosts: 107.167.186.8
    script: echo "no test in master"
    before_install:
    - openssl aes-256-cbc -K $encrypted_d523664c6f66_key -iv $encrypted_d523664c6f66_iv
      -in build/id_rsa.enc -out ~/.ssh/id_rsa -d
    - chmod 600 ~/.ssh/id_rsa
    after_success:
    - ssh root@107.167.186.8 'cd /root/work/go/y-transport-server && sh ./build/prd.sh'